### PR TITLE
Make general improvements

### PR DESCRIPTION
**Pull request by shmsr**
Improvements include:
- gofmt'ed and gofumpt'ed
- Simplify logic
- Pre-allocate wherever possible as it lead to fewer allocations
- Use better alternative functions to do the same work
- Upgrade dependencies
- Lower bound checks, etc.
- `ioutil` -> `io` or `os`

Most improvements might bring some performance improvement.

> NOTE: I noticed there are multiple spelling mistakes but it could be a breaking change if I correct them for users using your API. Let me know, what should I do?

Signed-off-by: subham sarkar <sarkar.subhams2@gmail.com>

### CODE REVIEW

**Comment by shmsr** [comment]
cc: @vividvilla @rhnvrm

**Comment by shmsr** [comment]
ping!

**Comment by shmsr** [comment]
ping!

**Comment by rhnvrm** [comment]
Hi

Could you please split these into smaller, easier-to-review PRs.  Also, would be helpful if you can open corresponding issues.

Closing this as it won't be possible to merge it into the codebase in this way.

> Let me know, what should I do?

In case you feel there could be improvements that could be breaking changes or you aren't certain about the performance impacts, please open an issue and we can discuss those.

**Pull request closed without merging**
